### ISSUE TITLE
DINI-AG-KIM Blog

### ISSUE THREAD

**Issue by sroertgen** [dini-ag-kim/blog#1]
I drafted a markdown based blog.

It is basically the same thing we already use in other places, but has the feature of using `tags` in the frontmatter.
This might be useful for tagging posts from the different KIM groups.

What else do we need?

You can view the blog under: https://dini-ag-kim.github.io/blog/

**Comment by sroertgen** [comment]
I'm also open for all kind of styling suggestions

**Comment by acka47** [comment]
Styling is fine for me. i noticed that the tags "OER-Metadatengruppe", "Curricula", "Titeldaten-Gruppe" are 

1. not consistent (I suggest "OER", "Curricula", "Titeldaten", "Lizenzen" etc.) 
2. not clickable, neither in the overview nor in a blog page.

I'd expect to be able to click a tag and get a list of all posts with the clicked tag.

**Comment by sroertgen** [comment]
> Styling is fine for me. i noticed that the tags "OER-Metadatengruppe", "Curricula", "Titeldaten-Gruppe" are
> 
>     1. not consistent (I suggest "OER", "Curricula", "Titeldaten", "Lizenzen" etc.)
> 
>     2. not clickable, neither in the overview nor in a blog page.
> 
> 
> I'd expect to be able to click a tag and get a list of all posts with the clicked tag.

re 1: Right. Though this is my fast drafting test posts. Whatever you put in the tags-frontmatter will be displayed there. So the authors of the blog should take care to use the right tags. Maybe we should add a list of suggested tags in the README.

re 2: They are now clickable and you will be directed to a page just showing the posts containing this tag.

**Comment by acka47** [comment]
> So the authors of the blog should take care to use the right tags. Maybe we should add a list of suggested tags in the README.

+1

> re 2: They are now clickable and you will be directed to a page just showing the posts containing this tag.

It works well. Thanks!
